inherit_from:
  - ~/.rubocop.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

# inherit_gem:
#     rubocop-shopify: rubocop.yml

# require:
#   - rubocop-rspec

# AllCops:
#   TargetRubyVersion: 2.7
#   Exclude:
#     - 'test/tmp/**/*'
#     - 'vendor/bundle/**/*'

# Style/MethodCallWithArgsParentheses:
#   Exclude:
#     - '**/Gemfile'

# Style/ClassAndModuleChildren:
#   Exclude:
#     - 'test/**/*'

# Style/StringLiterals:
#   Enabled: false
