
require 'date'
require 'active_support'
require 'active_support/core_ext'
require 'csv'

require 'fat_core/version'

require 'fat_core/array'
require 'fat_core/date'
require 'fat_core/enumerable'
require 'fat_core/hash'
require 'fat_core/kernel'
require 'fat_core/latex_eruby'
require 'fat_core/nil'
require 'fat_core/numeric'
require 'fat_core/period'
require 'fat_core/range'
require 'fat_core/string'
require 'fat_core/symbol'
require 'fat_core/evaluator'
require 'fat_core/column'
require 'fat_core/table'
