require 'fat_core/formatters/formatter'
require 'fat_core/formatters/aoa_formatter'
require 'fat_core/formatters/aoh_formatter'
require 'fat_core/formatters/org_formatter'
require 'fat_core/formatters/text_formatter'
require 'fat_core/formatters/term_formatter'
require 'fat_core/formatters/latex_formatter'
